version: "3.7"

services:
  backend:
    image: devansh1356/be_leave_portal:latest
    # build: 
    #   context: ./backend
    ports:
      - "8081:8081"
    # volumes:
    #   - ./leavePortal:/app             # Bind mount for live updates
    depends_on:
      - postgres
        
    networks:
      - s-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: navin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: devansh2
    ports:
      - 5435:5432
    networks:
      - s-network
    volumes:
      - postgres-s-data:/var/lib/postgresql/data

  frontend:
    image: devansh1356/fe_leave_portal:latest
    # build:
    #   context: ./frontend
    ports:
      - "5173:5173"
    # volumes:
    #   - ./leave-portal:/app           
    #   - /app/node_modules
    networks:
      - s-network
    environment:
      VITE_SECRET_KEY: mySecretKey12345
    depends_on:
      - backend

networks:
  s-network:
    driver: bridge

volumes:
  postgres-s-data:
